import Head from 'next/head';
export default function Home() {
  const requestUrl = `https://en.wikipedia.org/w/api.php?action=query&format=json&list=random&rnlimit=5&origin=*`;

  return (
    <>
      <Head>
        <title>Wikipedia Infinite Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hi</div>
    </>
  );
}
