import Head from 'next/head';
import { Header } from '@/components/Header';
import Link from 'next/link';
import { getLanguageTableData } from '@/utils/utils';
import { useState } from 'react';

export default function Home() {
  const languageTableData = getLanguageTableData();
  const [searchTerm, setSearchTerm] = useState('');
  const formattedSearchTerm = searchTerm.trim().toLocaleLowerCase();
  const filteredLanguages = languageTableData.filter(
    (language) =>
      language.code.toLowerCase().includes(formattedSearchTerm) ||
      language.name.toLowerCase().includes(formattedSearchTerm)
  );

  return (
    <>
      <Head>
        <title>Wikipedia Infinite Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-col items-center justify-center">
        <h1 className="mb-5 text-3xl font-medium">Wikipedia Infinite Scroll</h1>
        <p className="mb-5">
          Click on one of the counts to view the list of articles
        </p>
        <input
          className="rounded border border-black p-1 text-sm"
          onChange={(e) => setSearchTerm(e.target.value)}
          placeholder="Search for a language"
          type="text"
          value={searchTerm}
        />
        <div className="mt-5 max-h-80 w-11/12 overflow-scroll border-y border-black md:w-4/5">
          <table className="w-full border-collapse border border-black">
            <thead>
              <tr>
                <th>Language</th>
                <th>Code</th>
                <th>Featured Articles</th>
                <th>Good Articles</th>
                <th>Combined Articles</th>
              </tr>
            </thead>
            <tbody>
              {filteredLanguages.map((language) => (
                <tr key={language.name} className="border border-black ">
                  <td className="text-center">
                    <span>{language.name}</span>
                  </td>
                  <td className="text-center">
                    <span>{language.code}</span>
                  </td>
                  <td className="text-center">
                    {language.featuredCount > 0 ? (
                      <Link href={language.featuredUrl}>
                        {language.featuredCount}
                      </Link>
                    ) : (
                      0
                    )}
                  </td>
                  <td className="text-center">
                    {language.goodCount > 0 ? (
                      <Link href={language.goodUrl}>{language.goodCount}</Link>
                    ) : (
                      0
                    )}
                  </td>
                  <td className="text-center">
                    {language.bothCount > 0 ? (
                      <Link href={language.bothUrl}>{language.bothCount}</Link>
                    ) : (
                      0
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
