import Head from 'next/head';
import { ArticleList } from '@/components/ArticleList';
import { Header } from '@/components/Header';
import { Article, Language } from '@/utils/types';
import { getRandomArticleInfo } from '@/utils/utils';
import { useRouter } from 'next/router';
import { GetServerSidePropsContext } from 'next';
import languages from '../utils/languages.json';

type HomeProps = {
  articles: Article[];
  languages: Language[];
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const languageCodes = languages.map((language) => language.Wiki);
  const requestedLanguage = String(context.query.language);

  if (languageCodes.includes(requestedLanguage)) {
    return {
      props: {
        articles: await getRandomArticleInfo(requestedLanguage),
      },
    };
  }

  return {
    redirect: {
      destination: '/',
      permanent: false,
    },
  };
}

export default function RandomArticles({ articles }: HomeProps) {
  const { query } = useRouter();
  const language = languages.find(
    (language) => language.Wiki === String(query.language)
  );
  const languageName = language?.Language;
  const languageCode = language?.Wiki;
  const title = `Wikipedia Infinite Scroll - ${languageName}`;

  if (!language) return null;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header language={languageName} />
      <ArticleList articles={articles} language={languageCode} />
    </>
  );
}
