import Head from 'next/head';
import { ArticleList } from '@/pages/components/ArticleList';
import { Header } from '@/pages/components/Header';
import { Article } from '@/types';
import { getRandomArticleInfo } from '@/utils';
import { useRouter } from 'next/router';
import { GetServerSidePropsContext } from 'next';

type HomeProps = {
  articles: Article[];
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      articles: await getRandomArticleInfo(context.params?.language as string),
    },
  };
}

export default function Home({ articles }: HomeProps) {
  const router = useRouter();
  // TODO: If language is not recognized, redirect to english.
  // TODO: Create header with language options

  return (
    <>
      <Head>
        <title>Wikipedia Infinite Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ArticleList
        articles={articles}
        language={String(router.query.language)}
      />
    </>
  );
}
